# Numpy

* Numpy is numerical python

In [1]:
import numpy as np

In [4]:
val1 = np.array([[11,12,13],[14,15,16]])

In [5]:
val1

array([[11, 12, 13],
       [14, 15, 16]])

In [7]:
type(val1)

numpy.ndarray

In [8]:
val1.shape

(2, 3)

In [9]:
val1.dtype

dtype('int32')

In [10]:
val2 = np.arange(0,10,1)

In [11]:
val2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
val3 = np.ones((1,6) , dtype = int)

In [17]:
val3

array([[1, 1, 1, 1, 1, 1]])

In [21]:
val4 = np.linspace(14,34,3)

In [22]:
val4

array([14., 24., 34.])

In [23]:
val5 =  np.random.randint(5,20,size=(5,6))

In [24]:
val5

array([[ 9, 11, 18, 14, 19, 13],
       [17, 15, 16, 17,  9, 11],
       [ 9, 19,  9, 19, 16, 10],
       [16,  9,  9,  8,  5, 19],
       [17,  8, 18, 11, 18, 18]])

In [28]:
val6 = np.full((3,3,3),7)

In [29]:
val6

array([[[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]])

In [30]:
val7 = np.identity(4)

In [31]:
val7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
val8 = np.zeros((5,5), dtype = int)

In [35]:
val8

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [36]:
list = [21,22,23,24,25]
val9 = np.asarray(list)

In [37]:
val9

array([21, 22, 23, 24, 25])

In [38]:
x =(4,8)
y =(6,7)

In [39]:
np.divide(x,y)

array([0.66666667, 1.14285714])

In [40]:
np.multiply(x,y)

array([24, 56])

In [41]:
np.subtract(x,y)

array([-2,  1])

# Array Manipulation

In [42]:
val1 = np.array(np.random.randint(1,6,(6,3)))

In [43]:
val1

array([[3, 2, 1],
       [1, 3, 1],
       [4, 3, 4],
       [1, 1, 5],
       [5, 2, 2],
       [3, 2, 4]])

In [45]:
transpose_array = np.transpose(val1)

In [46]:
transpose_array

array([[3, 1, 4, 1, 5, 3],
       [2, 3, 3, 1, 2, 2],
       [1, 1, 4, 5, 2, 4]])

In [47]:
val2 = np.array(np.random.randint(5,8,(6,3)))

In [48]:
val2

array([[6, 7, 7],
       [7, 6, 7],
       [5, 7, 6],
       [6, 7, 5],
       [6, 6, 6],
       [5, 7, 5]])

In [49]:
val2.flatten()

array([6, 7, 7, 7, 6, 7, 5, 7, 6, 6, 7, 5, 6, 6, 6, 5, 7, 5])

Aggregation operation

In [50]:
data = np.random.randint(10,20,(6,8))

In [51]:
data

array([[19, 19, 17, 11, 14, 14, 14, 16],
       [14, 11, 15, 12, 10, 16, 16, 15],
       [15, 13, 19, 10, 12, 16, 18, 12],
       [14, 17, 18, 13, 15, 15, 19, 10],
       [15, 16, 17, 16, 11, 16, 10, 17],
       [13, 13, 10, 16, 17, 15, 12, 19]])

In [52]:
#sum

print(np.sum(data))
print(np.sum(data,axis=0))
print(np.sum(data,axis=1))

702
[90 89 96 78 79 92 89 89]
[124 109 115 121 118 115]


In [53]:
data.max()

19

In [54]:
data.min()

10

# Numpy array attributes

In [56]:
a1 = np.array([[11,12,13],[14,15,16]])
print(a1.shape)

(2, 3)


In [58]:
a2 = np.array([[11,12,13],[14,15,16]])
print(f"the dimension of a2:",a2.ndim)

the dimension of a2: 2


In [59]:
a3 = np.array([[21,22,23],[24,25,26]])
print(f"element in a3 ={a3.size}")

element in a3 =6


In [60]:
a4 = np.array([51,52,53])
print(a4.dtype)

int32
